export const environment = {
  production: true,
  ACCESS_KEY: 'ACCESS_KEY_FOR_CMS_PROVIDER',
  SECRET_ACCESS_KEY: 'SECRET_ACCESS_KEY_FOR_CMS_PROVIDER',
  REGION: 'REGION_FOR_CMS_PROVIDER',
  TABLE_NAME: 'TEST_TABLE_FOR_CMS_PROVIDER',
  BUCKET_NAME: 'TEST_BUCKET_FOR_CMS_PROVIDER'
};
